In [1]:
%pip install kagglehub

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Requirement already satisfied: kagglehub in /home/jovillalobos/.local/lib/python3.10/site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in /home/jovillalobos/.local/lib/python3.10/site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in /home/jovillalobos/.local/lib/python3.10/site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/python/mamba3/envs/Pytorch-kernel/lib/python3.10/site-packages (from requests->kagglehub) (2025.8.3)
Note: you may need to restart the kernel to use updated packages.

In [5]:
# data generation
from utils.data_generation import generate_data
df = generate_data()
df

Path to dataset files: /home/jovillalobos/.cache/kagglehub/datasets/ryandinh/agricultural-production-optimization/versions/1

,N,P,K,temperature,humidity,ph,rainfall,label,yield
0,90,42,43,20.879744,82.002744,6.502985,202.935536,rice,0.039027
1,85,58,41,21.770462,80.319644,7.038096,226.655537,rice,0.164952
2,60,55,44,23.004459,82.320763,7.840207,263.964248,rice,0.099274
3,74,35,40,26.491096,80.158363,6.980401,242.864034,rice,0.161181
4,78,42,42,20.130175,81.604873,7.628473,262.717340,rice,0.000000
...,...,...,...,...,...,...,...,...,...
2195,107,34,32,26.774637,66.413269,6.780064,177.774507,coffee,0.233947
2196,99,15,27,27.417112,56.636362,6.086922,127.924610,coffee,0.004838
2197,118,33,30,24.131797,67.225123,6.362608,173.322839,coffee,0.076744
2198,117,32,34,26.272418,52.127394,6.758793,127.175293,coffee,0.186023
2199,104,18,30,23.603016,60.396475,6.779833,140.937041,coffee,0.134246

In [6]:
# df is assumed to already exist with columns:
# N P K temperature humidity ph rainfall label yield

FEATURES_NUM = ["N", "P", "K", "temperature", "humidity", "ph", "rainfall"]
TARGET_CLASS = "label"
TARGET_REG = "yield"

X = df[FEATURES_NUM].copy()
y_class = df[TARGET_CLASS].copy()
y_reg = df[TARGET_REG].copy()

In [14]:
import pandas as pd
from utils.training_pipeline import TrainConfig, CropPipeline 
# Regressors
from sklearn.linear_model import (
    LogisticRegression
)

from sklearn.ensemble import (
    RandomForestClassifier,
)

cfg = TrainConfig(test_size=0.3, random_state=1293)

runner = CropPipeline(
    cfg=cfg,
    clf_model=LogisticRegression(max_iter=500),
    scale_numeric=True,
)

clf_metrics = runner.fit_classification(X, y_class, FEATURES_NUM)

pd.DataFrame([runner.results]).T

                     0
clf_accuracy  0.980303
clf_f1_macro  0.980312